#!/bin/bash
echo "game start"
start=$(date +%s) 
#执行程序
for ((i=1; i<=30; i ++))  
do  
    echo "this is the $i th push!">>test_batchpush.txt
    git add .
    git commit -m "test batch push"
    git push origin master
done  
end=$(date +%s)  
time=$(( $end - $start ))  
echo "本次运行时间： "$time"s"
echo "game over"